###data cleaning for climate variables
pacman::p_load('ncdf4','dplyr','matrixStats', 'CFtime')
#extract rainfall data (Jan 1981 (Col3) to Mar 2021 (Col485))
ncpath <- "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/"
ncname_r <- "rain"
ncfname_r <- paste(ncpath, ncname_r, ".nc", sep = "")
dname_r <- "rfe_merged"
ncin_r <- nc_open(ncfname_r)
print(ncin_r)
###get coordinate variables (lon, lat, time)
lat_r <- ncvar_get(ncin_r, "Y")
nlat_r<-dim(lat_r)
lon_r <- ncvar_get(ncin_r, "X")
nlon_r <- dim(lon_r)
print(c(nlon_r,nlat_r))

time_r <- ncvar_get(ncin_r, "T")
tunits_r <- ncatt_get(ncin_r, "T", "units")
nt_r <-dim(time_r)
nt_r
tunits_r
#get rain 
rin_array <- ncvar_get(ncin_r, dname_r)
dlname_r <- ncatt_get(ncin_r, dname_r, "long_name")
dunits_r<- ncatt_get(ncin_r, dname_r, "units")
fillvalue <- ncatt_get(ncin_r, dname_r, "_FillValue")
dim(rin_array)
title_r <- ncatt_get(ncin_r,0,"title")
institution_r <- ncatt_get(ncin_r,0,"institution")
datasource_r <-ncatt_get(ncin_r, 0, "source")
references_r <- ncatt_get(ncin_r, 0, "reference")
history_r <- ncatt_get(ncin_r, 0, "history")
Conventions_r <- ncatt_get(ncin_r,0,"Conventions")
nc_close(ncin_r) #close netCDF
ls()
#Reshaping from raster to rectangular
library(chron)
library(lattice)
library(RColorBrewer)
rustr <- strsplit(tunits_r$value, " ")
rdstr <- strsplit(unlist(rustr)[3], "-")
rmonth <- as.integer(unlist(rdstr)[2])
rday <- as.integer(unlist(rdstr)[3])
ryear <- as.integer(unlist(rdstr)[1])
chron(time_r,origin=c(rmonth, rday, ryear))


#reshape the array into vector for whole time
rin_vec_long <- as.vector(rin_array)
length(rin_vec_long)

rin_mat <- matrix(rin_vec_long, nrow=nlon_r*nlat_r, ncol = nt_r)
dim(rin_mat)
#head(na.omit(tmp_mat))
lonlat_r <- as.matrix(expand.grid(lon_r,lat_r))
rin_df02 <- data.frame(lonlat_r, rin_mat)
colnames(rin_df02)[1:2] <- c("lon", "lat")

# 1. Create a sequence of dates from January 1981
date_sequence_r <- seq(as.Date("1981-01-01"), by = "month", length.out = ncol(rin_df02) - 2)

# 2. Format the dates into "YYYY_MM" strings (e.g., "1981_01")
# %Y = 4-digit year, %m = 2-digit month
new_column_names_r <- format(date_sequence_r, "%Y_%m")

# 3. Assign the new names 
colnames(rin_df02)[3:ncol(rin_df02)] <- new_column_names_r

head(rin_df02)
write.csv(rin_df02, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/rain.csv", row.names=FALSE)

#20 years historical
rin_lonlat <- rin_df02[c(1:2)] #longitude and latitude
# rin_hist1 <- rin_df02[c(17:376)] #1982 March-2012 Feb monthly data without lon and lat
# rin_hist2 <- rin_df02[c(53:412)]# 1985 March-2015 Feb
# rin_hist3 <- rin_df02[c(101:460)]# 1989 March-2019 Feb
# rin_hist1 <- rin_df02[c(118:357)] #1990(Aug)-1991(Jan)~2009(Aug)-2010(Jan) but include by 2010 July. monthly data without lon and lat
# rin_hist2 <- rin_df02[c(142:381)] #1992(Aug)-1993(Jan)~2011(Aug)-2012(Jan) but include by 2012 July
rin_hist1 <- rin_df02[c(334:357)] #2008(Aug)-2009(Jan)~2009(Aug)-2010(Jan) but include by 2010 July. monthly data without lon and lat
rin_hist2 <- rin_df02[c(358:381)] #2010(Aug)-2011(Jan)~2011(Aug)-2012(Jan) but include by 2012 July

sd1 <- rowSds(as.matrix(rin_hist1), na.rm=TRUE) #standard deviation across month
sd2 <- rowSds(as.matrix(rin_hist2), na.rm=TRUE)
ave1 <- rowMeans(as.matrix(rin_hist1), na.rm=TRUE)
ave2 <- rowMeans(as.matrix(rin_hist2), na.rm=TRUE)

#10 years historical
rin_hist1_10yr <- rin_df02[c(238:357)] #2000(Aug)~2010(Jul). 120 months = 10 years
rin_hist2_10yr <- rin_df02[c(262:381)] #2002(Aug)~2012(Jul). 120 months = 10 years

sd1_10yr <- rowSds(as.matrix(rin_hist1_10yr), na.rm=TRUE)
sd2_10yr <- rowSds(as.matrix(rin_hist2_10yr), na.rm=TRUE)
ave1_10yr <- rowMeans(as.matrix(rin_hist1_10yr), na.rm=TRUE)
ave2_10yr <- rowMeans(as.matrix(rin_hist2_10yr), na.rm=TRUE)

#20 years historical
rin_hist1_20yr <- rin_df02[c(118:357)] #1990(Aug)~2010(Jul). 240 months = 20 years
rin_hist2_20yr <- rin_df02[c(142:381)] #1992(Aug)~2012(Jul). 240 months = 20 years

sd1_20yr <- rowSds(as.matrix(rin_hist1_20yr), na.rm=TRUE)
sd2_20yr <- rowSds(as.matrix(rin_hist2_20yr), na.rm=TRUE)
ave1_20yr <- rowMeans(as.matrix(rin_hist1_20yr), na.rm=TRUE)
ave2_20yr <- rowMeans(as.matrix(rin_hist2_20yr), na.rm=TRUE)

rain_year <- data.frame(rin_lonlat, sd1, sd2, ave1, ave2,
                        sd1_10yr, sd2_10yr, ave1_10yr, ave2_10yr,
                        sd1_20yr, sd2_20yr, ave1_20yr, ave2_20yr)
head(rain_year)
# NOTE: rain_year.csv is now generated by the standalone script (see below for temp additions)
# The combined rain+temp CSV is written after tmp_df02 is built

### total rainfall variability (year level)
rin1 <- rin_df02[c(334:357)] #2008(Aug)-2009(Jan)~2009(Aug)-2010(Jan) but include by 2010 July. monthly data without lon and lat
rin2 <- rin_df02[c(358:381)] #2010(Aug)-2011(Jan)~2011(Aug)-2012(Jan) but include by 2012 July

aus1 <- rin_hist1[, c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,
                      FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)]
aman1 <- rin_hist1[, c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,
                       FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] #August ~ January
boro1 <- rin_hist1[, c(FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,
                       TRUE,TRUE,TRUE,TRUE,TRUE,FALSE)]  #January ~ June
sdaus1 <- rowSds(as.matrix(aus1), na.rm=TRUE)
sdaman1 <- rowSds(as.matrix(aman1), na.rm=TRUE)
sdboro1 <- rowSds(as.matrix(boro1), na.rm=TRUE)
haus1 <- rowMeans(as.matrix(aus1), na.rm=TRUE)
haman1 <- rowMeans(as.matrix(aman1), na.rm=TRUE)
hboro1 <- rowMeans(as.matrix(boro1), na.rm=TRUE)

aus2 <- rin_hist2[, c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,
                      FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)]
aman2 <- rin_hist2[, c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,
                       FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] #August ~ January
boro2 <- rin_hist2[, c(FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,
                       TRUE,TRUE,TRUE,TRUE,TRUE,FALSE)]  #January ~ June
sdaus2 <- rowSds(as.matrix(aus2), na.rm=TRUE)
sdaman2 <- rowSds(as.matrix(aman2), na.rm=TRUE)
sdboro2 <- rowSds(as.matrix(boro2), na.rm=TRUE)
haus2 <- rowMeans(as.matrix(aus2), na.rm=TRUE)
haman2 <- rowMeans(as.matrix(aman2), na.rm=TRUE)
hboro2 <- rowMeans(as.matrix(boro2), na.rm=TRUE)
rin_data_sta1 <- data.frame(rin_lonlat, haus1, haman1, hboro1, sdaus1, sdaman1, sdboro1, 
                            haus2, haman2, hboro2, sdaus2, sdaman2, sdboro2)
head(rin_data_sta1)
write.csv(rin_data_sta1, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/rain_hist.csv", row.names=FALSE)

### survey year rainfall
# round 1 (baseline): 2011 Aug - 2012 July (12 months)
# round 2 (endline): 2013 Aug - 2014 July (12 months)
idx_r1_start <- which(colnames(rin_df02) == "2011_08")
idx_r1_end   <- which(colnames(rin_df02) == "2012_07")
idx_r2_start <- which(colnames(rin_df02) == "2013_08")
idx_r2_end   <- which(colnames(rin_df02) == "2014_07")

rin_survey1 <- rin_df02[, idx_r1_start:idx_r1_end] # 2011_08 ~ 2012_07 (cols 370:381)
rin_survey2 <- rin_df02[, idx_r2_start:idx_r2_end] # 2013_08 ~ 2014_07 (cols 394:405)

# Calculate average monthly rainfall (mm/month)
rain_survey_ave1 <- rowSums(as.matrix(rin_survey1), na.rm = TRUE)
rain_survey_ave2 <- rowSums(as.matrix(rin_survey2), na.rm = TRUE)

rin_data_sta2 <- data.frame(rin_lonlat, 
                            rain_survey_ave1 = rain_survey_ave1, 
                            rain_survey_ave2 = rain_survey_ave2)
head(rin_data_sta2)
write.csv(rin_data_sta2, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/rain_survey_year.csv", row.names=FALSE)

### lagged year rainfall
#rin_data3 <- rin_df02[c(1,2,353:448)] #2010 March -2018 Feb
#rin_data3$ls1 <- apply(rin_data3[3:10],1,sum)  #2011 Rabi
#rin_data3$lr1 <- apply(rin_data3[11:14],1,sum) #Kharif
#rin_data3$ls2 <- apply(rin_data3[39:46],1,sum) #2014 Rabi
#rin_data3$lr2 <- apply(rin_data3[47:50],1,sum) #Kharif
#rin_data3$ls3 <- apply(rin_data3[87:94],1,sum) #2018 Rabi
#rin_data3$lr3 <- apply(rin_data3[95:98],1,sum) #Kharif

#rin_data_sta3 <- subset(rin_data3,select=c(1,2,99:104))
###convert into csv
#head(rin_data_sta3)
#write.csv(rin_data_sta3, file.choose())

#extract temperature data
ncpath <- "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/"
ncname_t <- "temp"
ncfname_t <- paste(ncpath, ncname_t, ".nc", sep = "")
dname <- "tmean" #note: tmp means temperature

ncin_t <- nc_open(ncfname_t)
print(ncin_t)


#get coordinate variables (lon, lat, time)
lat_t <- ncvar_get(ncin_t, "Y")
nlat_t<-dim(lat_t)
lon_t <- ncvar_get(ncin_t, "X")
nlon_t <- dim(lon_t)
print(c(nlon_t,nlat_t))

time_t <- ncvar_get(ncin_t, "T")
tunits <- ncatt_get(ncin_t, "T", "units")
nt <-dim(time_t)
nt
tunits

#get temperature
tmp_array <- ncvar_get(ncin_t, dname)
dlname <- ncatt_get(ncin_t, dname, "long_name")
dunits<- ncatt_get(ncin_t, dname, "units")
fillvalue <- ncatt_get(ncin_t, dname, "_FillValue")
dim(tmp_array)
title <- ncatt_get(ncin_t,0,"title")
institution <- ncatt_get(ncin_t,0,"institution")
datasource <-ncatt_get(ncin_t, 0, "source")
references <- ncatt_get(ncin_t, 0, "reference")
history <- ncatt_get(ncin_t, 0, "history")
Conventions <- ncatt_get(ncin_t,0,"Conventions")
nc_close(ncin_t) #close netCDF
ls()
#Reshaping from raster to rectangular
library(chron)
library(lattice)
library(RColorBrewer)
tustr <- strsplit(tunits$value, " ")
tdstr <- strsplit(unlist(tustr)[3], "-")
tmonth <- as.integer(unlist(tdstr)[2])
tday <- as.integer(unlist(tdstr)[3])
tyear <- as.integer(unlist(tdstr)[1])
chron(time_t,origin=c(tmonth, tday, tyear))

#replace netCDF fill values with NA's
#tmp_array[tmp_array==fillvalue$value] <- NA
#length(na.omit(as.vector(tmp_array[,,1])))

#get a single time slice of the data, create R data frame and write a csv file
m <-300
tmp_slice <- tmp_array[,,m]
#image(lon_t,lat_t,tmp_slice,col=rev(brewer.pal(10,"RdBu")))
grid <- expand.grid(lon=lon_t, lat=lat_t)
cutpts <- c(-5,0,5,10,15,20,25,30,35,40,45)
levelplot(tmp_slice ~ lon * lat, data=grid, at=cutpts, cuts=11, pretty=T, 
          col.regions=(rev(brewer.pal(10,"RdBu"))))

#create data frame
lonlat_t <-as.matrix(expand.grid(lon_t,lat_t))
dim(lonlat_t)
tmp_vec <- as.vector(tmp_slice)
length(tmp_vec)
tmp_df01 <- data.frame(cbind(lonlat_t,tmp_vec))
names(tmp_df01)<- c("lon", "lat", paste(dname, as.character(m), sep = "_"))


#set path and filename
csvpath <- "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/"
csvname <- "tmp_1.csv"
csvfile <- paste(csvpath, csvname, sep = "")
#write.table(na.omit(tmp_df01), csvfile, row.names = FALSE,sep = ",")

#reshape the array into vector for whole time
tmp_vec_long <- as.vector(tmp_array)
length(tmp_vec_long)

tmp_mat <- matrix(tmp_vec_long, nrow=nlon_t*nlat_t, ncol = nt)
dim(tmp_mat)
#head(na.omit(tmp_mat))
lonlat_t <- as.matrix(expand.grid(lon_t,lat_t))
tmp_df02 <- data.frame(lonlat_t, tmp_mat)
colnames(tmp_df02)[1:2] <- c("lon", "lat") #1981 Jan~

# 1. Create a sequence of dates from January 1981
date_sequence_tmean <- seq(as.Date("1981-01-01"), by = "month", length.out = ncol(tmp_df02) - 2)

# 2. Format the dates into "YYYY_MM" strings (e.g., "1981_01")
# %Y = 4-digit year, %m = 2-digit month
new_column_names_tmean <- format(date_sequence_tmean, "%Y_%m")

# 3. Assign the new names to the time columns of your dataframe
colnames(tmp_df02)[3:ncol(tmp_df02)] <- new_column_names_tmean

### Temperature year-level variables (same column indices as rainfall)
# tmp_df02 has same structure as rin_df02: cols 1-2 = lon/lat, col 3+ = 1981-01~
# 2-year historical temperature
tmp_yr_hist1 <- tmp_df02[c(334:357)] #2008(Aug)~2010(Jul). 24 months = 2 years
tmp_yr_hist2 <- tmp_df02[c(358:381)] #2010(Aug)~2012(Jul). 24 months = 2 years

temp_sd1 <- rowSds(as.matrix(tmp_yr_hist1), na.rm=TRUE)
temp_sd2 <- rowSds(as.matrix(tmp_yr_hist2), na.rm=TRUE)
temp_ave1 <- rowMeans(as.matrix(tmp_yr_hist1), na.rm=TRUE)
temp_ave2 <- rowMeans(as.matrix(tmp_yr_hist2), na.rm=TRUE)

# 10-year historical temperature
tmp_yr_hist1_10yr <- tmp_df02[c(238:357)] #2000(Aug)~2010(Jul). 120 months = 10 years
tmp_yr_hist2_10yr <- tmp_df02[c(262:381)] #2002(Aug)~2012(Jul). 120 months = 10 years

temp_sd1_10yr <- rowSds(as.matrix(tmp_yr_hist1_10yr), na.rm=TRUE)
temp_sd2_10yr <- rowSds(as.matrix(tmp_yr_hist2_10yr), na.rm=TRUE)
temp_ave1_10yr <- rowMeans(as.matrix(tmp_yr_hist1_10yr), na.rm=TRUE)
temp_ave2_10yr <- rowMeans(as.matrix(tmp_yr_hist2_10yr), na.rm=TRUE)

# 20-year historical temperature
tmp_yr_hist1_20yr <- tmp_df02[c(118:357)] #1990(Aug)~2010(Jul). 240 months = 20 years
tmp_yr_hist2_20yr <- tmp_df02[c(142:381)] #1992(Aug)~2012(Jul). 240 months = 20 years

temp_sd1_20yr <- rowSds(as.matrix(tmp_yr_hist1_20yr), na.rm=TRUE)
temp_sd2_20yr <- rowSds(as.matrix(tmp_yr_hist2_20yr), na.rm=TRUE)
temp_ave1_20yr <- rowMeans(as.matrix(tmp_yr_hist1_20yr), na.rm=TRUE)
temp_ave2_20yr <- rowMeans(as.matrix(tmp_yr_hist2_20yr), na.rm=TRUE)

# Add temp variables to rain_year and export combined CSV
rain_year$temp_sd1 <- temp_sd1
rain_year$temp_sd2 <- temp_sd2
rain_year$temp_ave1 <- temp_ave1
rain_year$temp_ave2 <- temp_ave2
rain_year$temp_sd1_10yr <- temp_sd1_10yr
rain_year$temp_sd2_10yr <- temp_sd2_10yr
rain_year$temp_ave1_10yr <- temp_ave1_10yr
rain_year$temp_ave2_10yr <- temp_ave2_10yr
rain_year$temp_sd1_20yr <- temp_sd1_20yr
rain_year$temp_sd2_20yr <- temp_sd2_20yr
rain_year$temp_ave1_20yr <- temp_ave1_20yr
rain_year$temp_ave2_20yr <- temp_ave2_20yr
head(rain_year)
write.csv(rain_year, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/rain_year.csv", row.names=FALSE)

#historical temperature
tmp_lonlat <- tmp_df02[c(1:2)] #longitude and latitude
# tmp_hist1 <- tmp_df02[c(17:376)] #1982 March-2012 Feb monthly data without lon and lat
# tmp_hist2 <- tmp_df02[c(53:412)]# 1985 March-2015 Feb
# tmp_hist3 <- tmp_df02[c(101:460)]# 1989 March-2019 Feb
tmp_lonlat <- tmp_df02[c(1:2)] #longitude and latitude
tmp_hist1 <- tmp_df02[c(137:376)] #1992 March-2012 Feb monthly data without lon and lat
tmp_hist2 <- tmp_df02[c(173:412)]# 1995 March-2015 Feb
tmp_hist3 <- tmp_df02[c(221:460)]# 1999 March-2019 Feb
hst1 <- tmp_hist1[, c(TRUE, TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE)] # 20 years historical Kharif for 2011
hrt1 <- tmp_hist1[, c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE)]  # 20 years historical Rabi for 2011
sdst1 <- rowSds(as.matrix(hst1), na.rm=TRUE)
sdrt1 <- rowSds(as.matrix(hrt1), na.rm=TRUE)
hst1 <- rowMeans(hst1)
hrt1 <- rowMeans(hrt1)

hst2 <- tmp_hist2[, c(TRUE, TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE)] # 20 years historical Kharif for 2011
hrt2 <- tmp_hist2[, c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE)]  # 20 years historical Rabi for 2011
sdst2 <- rowSds(as.matrix(hst2), na.rm=TRUE)
sdrt2 <- rowSds(as.matrix(hrt2), na.rm=TRUE)
hst2 <- rowMeans(hst2)
hrt2 <- rowMeans(hrt2)
hst3 <- tmp_hist3[, c(TRUE, TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE)] # 20 years historical Rabi for 2011
hrt3 <- tmp_hist3[, c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE)]  # 20 years historical Kharif for 2011
sdst3 <- rowSds(as.matrix(hst3), na.rm=TRUE)
sdrt3 <- rowSds(as.matrix(hrt3), na.rm=TRUE)
hst3 <- rowMeans(hst3)
hrt3 <- rowMeans(hrt3)
tmp_data_sta1 <- data.frame(tmp_lonlat, hst1, hrt1,  sdst1, sdrt1, hst2, hrt2, sdst2, sdrt2,  hst3, hrt3, sdst3, sdrt3)


#survey year temperature
tmp_data2 <- tmp_df02[c(1,2,365:460)] #2011 March -2019 Feb
tmp_data2$ts1 <- apply(tmp_data2[3:10],1,mean) #2011 Kharif
tmp_data2$tr1 <- apply(tmp_data2[11:14],1,mean) #Rabi
tmp_data2$ts2 <- apply(tmp_data2[39:46],1,mean) #2014 Kharif
tmp_data2$tr2 <- apply(tmp_data2[47:50],1,mean) # Rabi
tmp_data2$ts3 <- apply(tmp_data2[87:94],1,mean) #2018 Kharif
tmp_data2$tr3 <- apply(tmp_data2[95:98],1,mean) #Rabi
tmp_data_sta2 <- subset(tmp_data2,select=c(1,2,99:104))

#lagged year temperature
tmp_data3 <- tmp_df02[c(1,2,353:448)] #2011 March -2019 
tmp_data3$lts1 <- apply(tmp_data3[3:10],1,mean) #2011 Kharif
tmp_data3$ltr1 <- apply(tmp_data3[11:14],1,mean) #Rabi
tmp_data3$lts2 <- apply(tmp_data3[39:46],1,mean) #2014 Kharif
tmp_data3$ltr2 <- apply(tmp_data3[47:50],1,mean) # Rabi
tmp_data3$lts3 <- apply(tmp_data3[87:94],1,mean) #2018 Kharif
tmp_data3$ltr3 <- apply(tmp_data3[95:98],1,mean) #Rabi
tmp_data_sta3 <- subset(tmp_data3,select=c(1,2,99:104))
###convert into csv
head(tmp_data_sta1)
write.csv(tmp_data_sta1, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmean_hist1.csv", row.names=FALSE)
head(tmp_data_sta2)
write.csv(tmp_data_sta2, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmean_hist2.csv", row.names=FALSE)
head(tmp_data_sta3)
write.csv(tmp_data_sta3, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmean_hist3.csv", row.names=FALSE)

#extract maximum and minimum temperature data
ncpath <- "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/"
ncname_t <- "month_merge_tmax"
ncfname_t <- paste(ncpath, ncname_t, ".nc", sep = "")
dname <- "temp" #note: tmp maximum temperature

ncin_t <- nc_open(ncfname_t)
print(ncin_t)


#get coordinate variables (lon, lat, time)
lat_t <- ncvar_get(ncin_t, "Lat")
nlat_t<-length(lat_t)
lon_t <- ncvar_get(ncin_t, "Lon")
nlon_t <- length(lon_t)
print(c(nlon_t,nlat_t))

time_t <- ncvar_get(ncin_t, "time")
tunits <- ncatt_get(ncin_t, "time", "units")
nt <-length(time_t)
nt
tunits

#get temperature
tmp_array <- ncvar_get(ncin_t, dname)
dlname <- ncatt_get(ncin_t, dname, "long_name")
dunits<- ncatt_get(ncin_t, dname, "units")
fillvalue <- ncatt_get(ncin_t, dname, "_FillValue")
dim(tmp_array)
title <- ncatt_get(ncin_t,0,"title")
institution <- ncatt_get(ncin_t,0,"institution")
datasource <-ncatt_get(ncin_t, 0, "source")
references <- ncatt_get(ncin_t, 0, "reference")
history <- ncatt_get(ncin_t, 0, "history")
Conventions <- ncatt_get(ncin_t,0,"Conventions")
nc_close(ncin_t) #close netCDF
ls()
#Reshaping from raster to rectangular
library(chron)
library(lattice)
library(RColorBrewer)
tustr <- strsplit(tunits$value, " ")
tdstr <- strsplit(unlist(tustr)[3], "-")
tmonth <- as.integer(unlist(tdstr)[2])
tday <- as.integer(unlist(tdstr)[3])
tyear <- as.integer(unlist(tdstr)[1])
chron(time_t,origin=c(tmonth, tday, tyear))

#replace netCDF fill values with NA's
#tmp_array[tmp_array==fillvalue$value] <- NA
#length(na.omit(as.vector(tmp_array[,,1])))

#get a single time slice of the data, create R data frame and write a csv file
m <-300
tmp_slice <- tmp_array[,,m]
#image(lon_t,lat_t,tmp_slice,col=rev(brewer.pal(10,"RdBu")))
grid <- expand.grid(lon=lon_t, lat=lat_t)
cutpts <- c(-5,0,5,10,15,20,25,30,35,40,45)
levelplot(tmp_slice ~ lon * lat, data=grid, at=cutpts, cuts=11, pretty=T, 
          col.regions=(rev(brewer.pal(10,"RdBu"))))

#create data frame
lonlat_t <-as.matrix(expand.grid(lon_t,lat_t))
dim(lonlat_t)
tmp_vec <- as.vector(tmp_slice)
length(tmp_vec)
tmp_df01 <- data.frame(cbind(lonlat_t,tmp_vec))
names(tmp_df01)<- c("lon", "lat", paste(dname, as.character(m), sep = "_"))


#set path and filename
csvpath <- "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/"
csvname <- "tmp_1.csv"
csvfile <- paste(csvpath, csvname, sep = "")
#write.table(na.omit(tmp_df01), csvfile, row.names = FALSE,sep = ",")

#reshape the array into vector for whole time
tmp_vec_long <- as.vector(tmp_array)
length(tmp_vec_long)

tmp_mat <- matrix(tmp_vec_long, nrow=nlon_t*nlat_t, ncol = nt)
dim(tmp_mat)
#head(na.omit(tmp_mat))
lonlat_t <- as.matrix(expand.grid(lon_t,lat_t))
tmp_df02 <- data.frame(lonlat_t, tmp_mat)
colnames(tmp_df02)[1:2] <- c("lon", "lat") #1981 Jan~

# 1. Create a sequence of dates from January 1981
print("Checking dims of tmp_df02 before names assignment:")
print(dim(tmp_df02))
date_sequence_tmax <- seq(as.Date("1981-01-01"), by = "month", length.out = ncol(tmp_df02) - 2)

# 2. Format the dates into "YYYY_MM" strings
new_column_names_tmax <- format(date_sequence_tmax, "%Y_%m")

# 3. Assign the new names 
colnames(tmp_df02)[3:ncol(tmp_df02)] <- new_column_names_tmax

#historical temperature
tmp_lonlat <- tmp_df02[c(1:2)] #longitude and latitude

#20 years historical
tmp_lonlat <- tmp_df02[c(1:2)] #longitude and latitude
# tmp_hist1 <- tmp_df02[c(17:376)] #1982 March-2012 Feb monthly data without lon and lat
# tmp_hist2 <- tmp_df02[c(53:412)]# 1985 March-2015 Feb
# tmp_hist3 <- tmp_df02[c(101:460)]# 1989 March-2019 Feb
# tmp_hist1 <- tmp_df02[c(118:357)] #1990(Aug)-1991(Jan)~2009(Aug)-2010(Jan) but include by 2010 July. monthly data without lon and lat
# tmp_hist2 <- tmp_df02[c(142:381)] #1992(Aug)-1993(Jan)~2011(Aug)-2012(Jan) but include by 2012 July
tmp_hist1 <- tmp_df02[c(334:357)] #2008(Aug)-2009(Jan)~2009(Aug)-2010(Jan) but include by 2010 July. monthly data without lon and lat
tmp_hist2 <- tmp_df02[c(358:381)] #2010(Aug)-2011(Jan)~2011(Aug)-2012(Jan) but include by 2012 July
aus1 <- tmp_hist1[, c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,
                      FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] #March ~ August
aman1 <- tmp_hist1[, c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,
                       FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] #August ~ January
boro1 <- tmp_hist1[, c(FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,
                       TRUE,TRUE,TRUE,TRUE,TRUE,FALSE)]  #January ~ June
sdaus1 <- rowSds(as.matrix(aus1), na.rm=TRUE)
sdaman1 <- rowSds(as.matrix(aman1), na.rm=TRUE)
sdboro1 <- rowSds(as.matrix(boro1), na.rm=TRUE)
haus1 <- rowMeans(as.matrix(aus1), na.rm=TRUE)
haman1 <- rowMeans(as.matrix(aman1), na.rm=TRUE)
hboro1 <- rowMeans(as.matrix(boro1), na.rm=TRUE)


aus2 <- tmp_hist2[, c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,
                      FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] 
aman2 <- tmp_hist2[, c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,
                       FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] #August ~ January
boro2 <- tmp_hist2[, c(FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,
                       TRUE,TRUE,TRUE,TRUE,TRUE,FALSE)]  #January ~ June
sdaus2 <- rowSds(as.matrix(aus2), na.rm=TRUE)
sdaman2 <- rowSds(as.matrix(aman2), na.rm=TRUE)
sdboro2 <- rowSds(as.matrix(boro2), na.rm=TRUE)
haus2 <- rowMeans(as.matrix(aus2), na.rm=TRUE)
haman2 <- rowMeans(as.matrix(aman2), na.rm=TRUE)
hboro2 <- rowMeans(as.matrix(boro2), na.rm=TRUE)
tmp_data_sta1 <- data.frame(tmp_lonlat, haus1, haman1, hboro1, sdaus1, sdaman1, sdboro1, 
                            haus2, haman2, hboro2, sdaus2, sdaman2, sdboro2)
head(tmp_data_sta1)
write.csv(tmp_data_sta1, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmax_hist.csv", row.names=FALSE)

# Dummy variables > 35C 
tmax_dummy1 <- as.data.frame(ifelse(tmp_hist1 > 35, 1, 0))
tmax_dummy2 <- as.data.frame(ifelse(tmp_hist2 > 35, 1, 0))

# Seasons for 1
aus1_dummy <- tmax_dummy1[, c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,
                              FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] 
aman1_dummy <- tmax_dummy1[, c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,
                               FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)]
boro1_dummy <- tmax_dummy1[, c(FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,
                               TRUE,TRUE,TRUE,TRUE,TRUE,FALSE)]
sum_aus1_dummy <- rowSums(as.matrix(aus1_dummy), na.rm=TRUE)/2
sum_aman1_dummy <- rowSums(as.matrix(aman1_dummy), na.rm=TRUE)/2
sum_boro1_dummy <- rowSums(as.matrix(boro1_dummy), na.rm=TRUE)/2

# Seasons for 2
aus2_dummy <- tmax_dummy2[, c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,
                              FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)] 
aman2_dummy <- tmax_dummy2[, c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,
                               FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)]
boro2_dummy <- tmax_dummy2[, c(FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,
                               TRUE,TRUE,TRUE,TRUE,TRUE,FALSE)]
sum_aus2_dummy <- rowSums(as.matrix(aus2_dummy), na.rm=TRUE)/2
sum_aman2_dummy <- rowSums(as.matrix(aman2_dummy), na.rm=TRUE)/2
sum_boro2_dummy <- rowSums(as.matrix(boro2_dummy), na.rm=TRUE)/2

tmax_hist1 <- data.frame(tmp_lonlat, aus=sum_aus1_dummy, aman=sum_aman1_dummy, boro=sum_boro1_dummy)
tmax_hist2 <- data.frame(tmp_lonlat, aus=sum_aus2_dummy, aman=sum_aman2_dummy, boro=sum_boro2_dummy)
tmax_hist <- data.frame(tmp_lonlat, sum_aus1_dummy, sum_aman1_dummy, sum_boro1_dummy, 
                        sum_aus2_dummy, sum_aman2_dummy, sum_boro2_dummy)

write.csv(tmax_hist1, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmax_hist1.csv", row.names=FALSE)
write.csv(tmax_hist2, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmax_hist2.csv", row.names=FALSE)
write.csv(tmax_hist, "C:/Users/mm_wi/Documents/research/brac_credit/data/weather/tmax_hist.csv", row.names=FALSE)
